baseURL: "https://ngeorge.net"
title: "Nikhil George"
theme: PaperMod

# URL settings (Correct placement)
uglyURLs: false
canonifyURLs: true
relativeURLs: false

enableInlineShortcodes: true
enableRobotsTXT: true
publishDir: "docs"

pagination:
  pagerSize: 20

taxonomies:
  tag: tags

menu:
  main:
    - name: Research
      url: /research/
      weight: 1
    - name: Notes
      url: /notes/
      weight: 2
    - name: About
      url: /about/
      weight: 3

params:
  description: "Nikhil George's academic research on technology, skills, and labor markets"
  author: "Nikhil George"
  DateFormat: "January 2006"
  defaultTheme: light
  hideFooter: false
  disableThemeToggle: true
  ShowShareButtons: false
  ShowReadingTime: false
  disableSpecial1stPost: true
  disableAnchoredHeadings: true
  ShowPostNavLinks: false
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowAllPagesInArchive: false
  MainSections: ["research", "notes"]
  ShowToc: false
  disableScrollToTop: true
  TocOpen: true
  ShowWordCount: false
  UseHugoToc: true
  comments: false
  math: true

  footer:
    content: "© 2024 Nikhil George · Built with Hugo and Pascal Michaillat's Minimalist Academic Template"

  profileMode:
    enabled: true
    title: "Nikhil George"
    subtitle: "PhD Candidate (ABD) in Information Systems at Carnegie Mellon University's Heinz College. I harness big data and AI models to explore how technological change reshapes labor markets, skills, and organizations. Through innovative measurement approaches, I study worker mobility, skill transitions, and organizational transformation in our evolving digital economy. I am on the academic job market - find my CV and contact information below."
    imageUrl: "/images/profile.webp"
    imageWidth: 200
    imageHeight: 200
    buttons:
      - name: Research
        url: /research/
      - name: Notes
        url: /notes/
      - name: About
        url: /about/

  socialIcons:
    - name: cv
      url: "/cv/nikhil-george-cv.pdf"
    - name: github
      url: "https://github.com/nikhilgeorge2"
    - name: google-scholar
      url: "https://scholar.google.com/citations?user=13ecWosAAAAJ"
    - name: twitter
      url: "https://x.com/nikilgeorge"
    - name: email
      url: "mailto:ngeorge1@andrew.cmu.edu"

  assets:
    disableScrollBarStyle: true
    css: ["css/extended/academic.css"]
    favicon: "/images/favicon.png"
    katex: true

  customFont:
    enable: true
    fontFamily: "EB Garamond"
    fontLink: "https://fonts.googleapis.com/css2?family=EB+Garamond:wght@400;500&display=swap"

markup:
  goldmark:
    renderer:
      unsafe: false
  highlight:
    guessSyntax: true
    style: github
  tableOfContents:
    endLevel: 2
    ordered: false
    startLevel: 2

titleCaseStyle: "none"